name: e_product_order_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  google_sign_in: ^6.2.1
  image_picker: ^0.8.9
  intl: ^0.19.0
  dots_indicator: ^3.0.0

  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0

  flutter_image_compress: ^2.3.0

  firebase_core: ^2.27.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.5
  json_serializable: ^6.8.0
  freezed: ^2.3.5


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DraftingMono
      fonts:
        - asset: assets/fonts/DraftingMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/DraftingMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DraftingMono-Light.ttf
          weight: 300
        - asset: assets/fonts/DraftingMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/DraftingMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/DraftingMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DraftingMono-Bold.ttf
          weight: 700

    - family: RentStrike
      fonts:
        - asset: assets/fonts/RENTSTRIKE.otf
          weight: 800

