// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJtbkoTWbM7N6N7B9vIZbc7dF49R2hTz0',
    appId: '1:599238218045:web:9f2017ca9d241a76987554',
    messagingSenderId: '599238218045',
    projectId: 'product-order-9d38f',
    authDomain: 'product-order-9d38f.firebaseapp.com',
    storageBucket: 'product-order-9d38f.appspot.com',
    measurementId: 'G-FG93SZ0FED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOmMSRd7vaD7Q7jbF5YdBBC_0DGNsjv6U',
    appId: '1:599238218045:android:2ded30ae05fc8275987554',
    messagingSenderId: '599238218045',
    projectId: 'product-order-9d38f',
    storageBucket: 'product-order-9d38f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8AfRItaqCZF5SDm5iPJsTb00FCNglFiI',
    appId: '1:599238218045:ios:976bd2b40d46d93c987554',
    messagingSenderId: '599238218045',
    projectId: 'product-order-9d38f',
    storageBucket: 'product-order-9d38f.appspot.com',
    iosClientId: '599238218045-fgstk4kq49u9bokjplo9jkdtm36hackm.apps.googleusercontent.com',
    iosBundleId: 'com.noyohelsinki.eProductOrderFlutter',
  );
}
